version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    depends_on:
      - server
    volumes:
      - ./client:/app/
      - /app/node_modules
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
    environment:
      - PGDATABASE=postgres
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
  db:
    build:
      context: ./db
    volumes:
      - todo-supertest-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  todo-supertest-volume:
